[book]
authors = ["Christoph Singewald"]
language = "de"
multilingual = true
src = "src"


[build]
build-dir = "../../book/de"
create-missing = false
use-default-preprocessors = true


[output.html.search]
limit-results = 20
use-boolean-and = true
boost-title = 2
boost-hierarchy = 2
boost-paragraph = 1
expand = true
heading-split-level = 2

[output.html.fold]
enable = true
level = 0

[output.markdown]